name: Flutter CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.7'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Analyze code
      run: flutter analyze
    
    # Tests désactivés temporairement - À réactiver après création de vrais tests
    # - name: Run tests
    #   run: flutter test --coverage
    
    # Formatting check désactivé temporairement
    # - name: Check formatting
    #   run: dart format --output=none --set-exit-if-changed .
    
    - name: Build APK
      run: flutter build apk --debug
    
    - name: Build iOS (if on macOS)
      if: runner.os == 'macOS'
      run: flutter build ios --debug --no-codesign